### ISSUE TITLE
Size on SwiftUI

### ISSUE THREAD

**Issue by baronha** [iconoir-icons/iconoir-swift#10]
Size not working SwiftUI like example:

```
import SwiftUI
import Iconoir_swift

struct ContentView: View {
    var body: some View {
        Iconoir.bell.asImage
            .foregroundColor(.blue)
            .font(.system(size: 100))
    }
}
```

==> The icon remains unchanged in size

**Comment by YoRolling** [comment]
I think you should use `resizable`  modifier
```swiftui
import SwiftUI
import Iconoir_swift

struct ContentView: View {
    var body: some View {
        Iconoir.bell.asImage
            .resizable()
            .foregroundColor(.blue)
            .frame(width:200,height:200)
    }
}
```

**Comment by mkaulfers** [comment]
> I think you should use `resizable` modifier
> 
> ```
> import SwiftUI
> import Iconoir_swift
> 
> struct ContentView: View {
>     var body: some View {
>         Iconoir.bell.asImage
>             .resizable()
>             .foregroundColor(.blue)
>             .frame(width:200,height:200)
>     }
> }
> ```

Yes this is the correct usage.

**Comment by baronha** [comment]
too blur @mkaulfers 

<img width="376" alt="Screenshot 2024-03-26 at 23 56 01" src="https://github.com/iconoir-icons/iconoir-swift/assets/23580920/08545504-0660-4e38-8ce1-1ba7c0f6b485">
